version: '3.9'

services:
  frontend:
    build: ./frontend
    container_name: hevial-frontend

  nginx:
    image: nginx:alpine
    container_name: hevial-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend

  backend:
    build: ./backend
    container_name: hevial-backend
    ports:
      - "5000:5000"